# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Jonathan/Documents/Projects/pkgj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Jonathan/Documents/Projects/pkgj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Jonathan/Documents/Projects/pkgj/CMakeFiles /Users/Jonathan/Documents/Projects/pkgj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Jonathan/Documents/Projects/pkgj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named copy

# Build rule for target.
copy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 copy
.PHONY : copy

# fast build rule for target.
copy/fast:
	$(MAKE) -f CMakeFiles/copy.dir/build.make CMakeFiles/copy.dir/build
.PHONY : copy/fast

#=============================================================================
# Target rules for targets named send

# Build rule for target.
send: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 send
.PHONY : send

# fast build rule for target.
send/fast:
	$(MAKE) -f CMakeFiles/send.dir/build.make CMakeFiles/send.dir/build
.PHONY : send/fast

#=============================================================================
# Target rules for targets named pkgj.vpk

# Build rule for target.
pkgj.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pkgj.vpk
.PHONY : pkgj.vpk

# fast build rule for target.
pkgj.vpk/fast:
	$(MAKE) -f CMakeFiles/pkgj.vpk.dir/build.make CMakeFiles/pkgj.vpk.dir/build
.PHONY : pkgj.vpk/fast

#=============================================================================
# Target rules for targets named eboot.bin

# Build rule for target.
eboot.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eboot.bin
.PHONY : eboot.bin

# fast build rule for target.
eboot.bin/fast:
	$(MAKE) -f CMakeFiles/eboot.bin.dir/build.make CMakeFiles/eboot.bin.dir/build
.PHONY : eboot.bin/fast

#=============================================================================
# Target rules for targets named pkgj

# Build rule for target.
pkgj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pkgj
.PHONY : pkgj

# fast build rule for target.
pkgj/fast:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/build
.PHONY : pkgj/fast

#=============================================================================
# Target rules for targets named fmtproject

# Build rule for target.
fmtproject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmtproject
.PHONY : fmtproject

# fast build rule for target.
fmtproject/fast:
	$(MAKE) -f CMakeFiles/fmtproject.dir/build.make CMakeFiles/fmtproject.dir/build
.PHONY : fmtproject/fast

#=============================================================================
# Target rules for targets named Boost

# Build rule for target.
Boost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Boost
.PHONY : Boost

# fast build rule for target.
Boost/fast:
	$(MAKE) -f CMakeFiles/Boost.dir/build.make CMakeFiles/Boost.dir/build
.PHONY : Boost/fast

pkgi.obj: pkgi.cpp.obj

.PHONY : pkgi.obj

# target to build an object file
pkgi.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi.cpp.obj
.PHONY : pkgi.cpp.obj

pkgi.i: pkgi.cpp.i

.PHONY : pkgi.i

# target to preprocess a source file
pkgi.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi.cpp.i
.PHONY : pkgi.cpp.i

pkgi.s: pkgi.cpp.s

.PHONY : pkgi.s

# target to generate assembly for a file
pkgi.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi.cpp.s
.PHONY : pkgi.cpp.s

pkgi_aes128.obj: pkgi_aes128.c.obj

.PHONY : pkgi_aes128.obj

# target to build an object file
pkgi_aes128.c.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_aes128.c.obj
.PHONY : pkgi_aes128.c.obj

pkgi_aes128.i: pkgi_aes128.c.i

.PHONY : pkgi_aes128.i

# target to preprocess a source file
pkgi_aes128.c.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_aes128.c.i
.PHONY : pkgi_aes128.c.i

pkgi_aes128.s: pkgi_aes128.c.s

.PHONY : pkgi_aes128.s

# target to generate assembly for a file
pkgi_aes128.c.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_aes128.c.s
.PHONY : pkgi_aes128.c.s

pkgi_config.obj: pkgi_config.cpp.obj

.PHONY : pkgi_config.obj

# target to build an object file
pkgi_config.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_config.cpp.obj
.PHONY : pkgi_config.cpp.obj

pkgi_config.i: pkgi_config.cpp.i

.PHONY : pkgi_config.i

# target to preprocess a source file
pkgi_config.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_config.cpp.i
.PHONY : pkgi_config.cpp.i

pkgi_config.s: pkgi_config.cpp.s

.PHONY : pkgi_config.s

# target to generate assembly for a file
pkgi_config.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_config.cpp.s
.PHONY : pkgi_config.cpp.s

pkgi_db.obj: pkgi_db.cpp.obj

.PHONY : pkgi_db.obj

# target to build an object file
pkgi_db.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_db.cpp.obj
.PHONY : pkgi_db.cpp.obj

pkgi_db.i: pkgi_db.cpp.i

.PHONY : pkgi_db.i

# target to preprocess a source file
pkgi_db.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_db.cpp.i
.PHONY : pkgi_db.cpp.i

pkgi_db.s: pkgi_db.cpp.s

.PHONY : pkgi_db.s

# target to generate assembly for a file
pkgi_db.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_db.cpp.s
.PHONY : pkgi_db.cpp.s

pkgi_dialog.obj: pkgi_dialog.c.obj

.PHONY : pkgi_dialog.obj

# target to build an object file
pkgi_dialog.c.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_dialog.c.obj
.PHONY : pkgi_dialog.c.obj

pkgi_dialog.i: pkgi_dialog.c.i

.PHONY : pkgi_dialog.i

# target to preprocess a source file
pkgi_dialog.c.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_dialog.c.i
.PHONY : pkgi_dialog.c.i

pkgi_dialog.s: pkgi_dialog.c.s

.PHONY : pkgi_dialog.s

# target to generate assembly for a file
pkgi_dialog.c.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_dialog.c.s
.PHONY : pkgi_dialog.c.s

pkgi_download.obj: pkgi_download.cpp.obj

.PHONY : pkgi_download.obj

# target to build an object file
pkgi_download.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_download.cpp.obj
.PHONY : pkgi_download.cpp.obj

pkgi_download.i: pkgi_download.cpp.i

.PHONY : pkgi_download.i

# target to preprocess a source file
pkgi_download.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_download.cpp.i
.PHONY : pkgi_download.cpp.i

pkgi_download.s: pkgi_download.cpp.s

.PHONY : pkgi_download.s

# target to generate assembly for a file
pkgi_download.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_download.cpp.s
.PHONY : pkgi_download.cpp.s

pkgi_downloader.obj: pkgi_downloader.cpp.obj

.PHONY : pkgi_downloader.obj

# target to build an object file
pkgi_downloader.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_downloader.cpp.obj
.PHONY : pkgi_downloader.cpp.obj

pkgi_downloader.i: pkgi_downloader.cpp.i

.PHONY : pkgi_downloader.i

# target to preprocess a source file
pkgi_downloader.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_downloader.cpp.i
.PHONY : pkgi_downloader.cpp.i

pkgi_downloader.s: pkgi_downloader.cpp.s

.PHONY : pkgi_downloader.s

# target to generate assembly for a file
pkgi_downloader.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_downloader.cpp.s
.PHONY : pkgi_downloader.cpp.s

pkgi_menu.obj: pkgi_menu.cpp.obj

.PHONY : pkgi_menu.obj

# target to build an object file
pkgi_menu.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_menu.cpp.obj
.PHONY : pkgi_menu.cpp.obj

pkgi_menu.i: pkgi_menu.cpp.i

.PHONY : pkgi_menu.i

# target to preprocess a source file
pkgi_menu.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_menu.cpp.i
.PHONY : pkgi_menu.cpp.i

pkgi_menu.s: pkgi_menu.cpp.s

.PHONY : pkgi_menu.s

# target to generate assembly for a file
pkgi_menu.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_menu.cpp.s
.PHONY : pkgi_menu.cpp.s

pkgi_sha256.obj: pkgi_sha256.c.obj

.PHONY : pkgi_sha256.obj

# target to build an object file
pkgi_sha256.c.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_sha256.c.obj
.PHONY : pkgi_sha256.c.obj

pkgi_sha256.i: pkgi_sha256.c.i

.PHONY : pkgi_sha256.i

# target to preprocess a source file
pkgi_sha256.c.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_sha256.c.i
.PHONY : pkgi_sha256.c.i

pkgi_sha256.s: pkgi_sha256.c.s

.PHONY : pkgi_sha256.s

# target to generate assembly for a file
pkgi_sha256.c.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_sha256.c.s
.PHONY : pkgi_sha256.c.s

pkgi_vita.obj: pkgi_vita.cpp.obj

.PHONY : pkgi_vita.obj

# target to build an object file
pkgi_vita.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_vita.cpp.obj
.PHONY : pkgi_vita.cpp.obj

pkgi_vita.i: pkgi_vita.cpp.i

.PHONY : pkgi_vita.i

# target to preprocess a source file
pkgi_vita.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_vita.cpp.i
.PHONY : pkgi_vita.cpp.i

pkgi_vita.s: pkgi_vita.cpp.s

.PHONY : pkgi_vita.s

# target to generate assembly for a file
pkgi_vita.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_vita.cpp.s
.PHONY : pkgi_vita.cpp.s

pkgi_vitahttp.obj: pkgi_vitahttp.cpp.obj

.PHONY : pkgi_vitahttp.obj

# target to build an object file
pkgi_vitahttp.cpp.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_vitahttp.cpp.obj
.PHONY : pkgi_vitahttp.cpp.obj

pkgi_vitahttp.i: pkgi_vitahttp.cpp.i

.PHONY : pkgi_vitahttp.i

# target to preprocess a source file
pkgi_vitahttp.cpp.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_vitahttp.cpp.i
.PHONY : pkgi_vitahttp.cpp.i

pkgi_vitahttp.s: pkgi_vitahttp.cpp.s

.PHONY : pkgi_vitahttp.s

# target to generate assembly for a file
pkgi_vitahttp.cpp.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_vitahttp.cpp.s
.PHONY : pkgi_vitahttp.cpp.s

pkgi_zrif.obj: pkgi_zrif.c.obj

.PHONY : pkgi_zrif.obj

# target to build an object file
pkgi_zrif.c.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_zrif.c.obj
.PHONY : pkgi_zrif.c.obj

pkgi_zrif.i: pkgi_zrif.c.i

.PHONY : pkgi_zrif.i

# target to preprocess a source file
pkgi_zrif.c.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_zrif.c.i
.PHONY : pkgi_zrif.c.i

pkgi_zrif.s: pkgi_zrif.c.s

.PHONY : pkgi_zrif.s

# target to generate assembly for a file
pkgi_zrif.c.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/pkgi_zrif.c.s
.PHONY : pkgi_zrif.c.s

puff.obj: puff.c.obj

.PHONY : puff.obj

# target to build an object file
puff.c.obj:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/puff.c.obj
.PHONY : puff.c.obj

puff.i: puff.c.i

.PHONY : puff.i

# target to preprocess a source file
puff.c.i:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/puff.c.i
.PHONY : puff.c.i

puff.s: puff.c.s

.PHONY : puff.s

# target to generate assembly for a file
puff.c.s:
	$(MAKE) -f CMakeFiles/pkgj.dir/build.make CMakeFiles/pkgj.dir/puff.c.s
.PHONY : puff.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... copy"
	@echo "... send"
	@echo "... edit_cache"
	@echo "... pkgj.vpk"
	@echo "... eboot.bin"
	@echo "... pkgj"
	@echo "... fmtproject"
	@echo "... rebuild_cache"
	@echo "... Boost"
	@echo "... pkgi.obj"
	@echo "... pkgi.i"
	@echo "... pkgi.s"
	@echo "... pkgi_aes128.obj"
	@echo "... pkgi_aes128.i"
	@echo "... pkgi_aes128.s"
	@echo "... pkgi_config.obj"
	@echo "... pkgi_config.i"
	@echo "... pkgi_config.s"
	@echo "... pkgi_db.obj"
	@echo "... pkgi_db.i"
	@echo "... pkgi_db.s"
	@echo "... pkgi_dialog.obj"
	@echo "... pkgi_dialog.i"
	@echo "... pkgi_dialog.s"
	@echo "... pkgi_download.obj"
	@echo "... pkgi_download.i"
	@echo "... pkgi_download.s"
	@echo "... pkgi_downloader.obj"
	@echo "... pkgi_downloader.i"
	@echo "... pkgi_downloader.s"
	@echo "... pkgi_menu.obj"
	@echo "... pkgi_menu.i"
	@echo "... pkgi_menu.s"
	@echo "... pkgi_sha256.obj"
	@echo "... pkgi_sha256.i"
	@echo "... pkgi_sha256.s"
	@echo "... pkgi_vita.obj"
	@echo "... pkgi_vita.i"
	@echo "... pkgi_vita.s"
	@echo "... pkgi_vitahttp.obj"
	@echo "... pkgi_vitahttp.i"
	@echo "... pkgi_vitahttp.s"
	@echo "... pkgi_zrif.obj"
	@echo "... pkgi_zrif.i"
	@echo "... pkgi_zrif.s"
	@echo "... puff.obj"
	@echo "... puff.i"
	@echo "... puff.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

